Update tf-validate-all.yml

diff --git a/.github/workflows/tf-validate-all.yml b/.github/workflows/tf-validate-all.yml
--- a/.github/workflows/tf-validate-all.yml
+++ b/.github/workflows/tf-validate-all.yml
@@ -26,7 +26,30 @@ jobs:
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v3
 
-    - name: Validate All Terraform
-      run: ./.github/tf-validate-all.sh ./
+    - name: Validate - Azure - Modules
+      run: | 
+        ./.github/tf-validate-all.sh ./microsoft-azure/modules
+        if [ $? -ne 0 ]; then
+          echo "Validation failed for Azure Modules."
+          exit 1
+        fi
+      working-directory: ${{ github.workspaces }}
+
+    - name: Validate - Azure - Quickstarts
+      run: |
+        ./.github/tf-validate-all.sh ./microsoft-azure/quickstarts
+        if [ $? -ne 0 ]; then
+          echo "Validation failed for Azure Modules."
+          exit 1
+        fi
+      working-directory: ${{ github.workspaces }}
+
+    - name: Validate - Azure - Workloads
+      run: |
+        ./.github/tf-validate-all.sh ./microsoft-azure/workloads
+        if [ $? -ne 0 ]; then
+          echo "Validation failed for Azure Modules."
+          exit 1
+        fi
       working-directory: ${{ github.workspaces }}
         
